name: ci

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out
        uses: actions/checkout@v2
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./8.0/bullseye/fpm
          file: ./8.0/bullseye/fpm/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/php:latest
